import type { Metadata } from "next";
import "./globals.css";
import "@/app/assets/scss/style.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-gray-800">{children}</body>
    </html>
  );
}
